development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: login
  :user_name: testguardian84@gmail.com
  :password: <key_code>
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: login
  :user_name: testguardian84@gmail.com
  :password: <key_code>
  :enable_starttls_auto: true
  